services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskflow_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: