spring.application.name=task_flow

# It tells where the database is 
spring.datasource.url= jdbc:mysql://localhost:3306/taskflow
# Username to connect
spring.datasource.username=root
# Password for the above user
spring.datasource.password=Admin@123
# It tells which driver to use for connecting to this database url
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Auto create table and persist data for the entity
spring.jpa.hibernate.ddl-auto=update





# jwt-secret-key
jwt.secret=thisisaverylongandsecuresecretkey32bytesminimum

# jwt-expriy
jwt.expiry=259200000